// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	gpt "github.com/mizy/llama-cpp-gpt-api/internal/handler/gpt"
	"github.com/mizy/llama-cpp-gpt-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/v1/chat/completions",
				Handler: gpt.ChatCompletionsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/embeddings",
				Handler: gpt.EmbeddingsHandler(serverCtx),
			},
		},
	)
}
